Add files via upload

diff --git a/obj-classes b/obj-classes
--- a/obj-classes
+++ b/obj-classes
@@ -7,30 +7,34 @@
 # "bash-object" scripts are licensed under the GNU General Public License v3.0
 # author: pal@kochis.hu
 #
-# A) @obj-debug
-# C) @object-list and object-list
-# D) @obj-dictionary and obj-error-messages
-# E) Change error helper
-# F) @obj and --help
-# G) @obj-backup-variables
+# A) @obj@list and object-list
+# B) @obj@info
+# C) @obj@dictionary and obj-error-messages
+# D) Change error helper
+# E) @obj@backup-variables
 ################################################################################
 [[ $(type -t objCconstruct) != function ]] && exit  # prevents unwanted load
 
-# A) @obj-debug
-((${objects["ID@obj-debug"]:-0} == 0)) && obj @ obj-create @obj-debug \
- objC_Public obj-debug '{ local i
-  declare -p obj_details$this obj_data$this; for i in "${!this_data[@]}"; do declare -p objV_${this_data[$i]}; done
- }'
-
-# C) @object-list and object-list
-((${objects["ID@object-list"]:-0} == 0)) && obj @ obj-create @object-list \
+# A) @obj@list and object-list
+((${objects["ID@obj@list"]:-0} == 0)) && obj @obj obj-create @list \
  objC_Public obj-list '{
   local i; for i in "${!objects[@]}"; do [[ $i == @(ID|ID*\ *) ]] && echo \"${i#ID}\" || { [[ $i == ID* ]] && echo ${i#ID}; }; done
  }' objC_Default obj-list
-((${objects["IDobject-list"]:-0} == 0)) && obj @object-list obj-create object-list
+((${objects["IDobject-list"]:-0} == 0)) && obj @obj@list obj-create object-list
 
-# D) @obj-dictionary and obj-error-messages
-((${objects["ID@obj-dictionary"]:-0} == 0)) && obj @ obj-create @obj-dictionary \
+# B) @obj@info
+((${objects["ID@obj@info"]:-0} == 0)) && obj @obj obj-create @info \
+ objC_Public obj-info '{ local i
+  echo -e "\nObject: ${this[1]}\nClass:  ${this_details[parent]}\n"
+  echo -e "Default method: ${this_details[D]}\nInit method:    ${this_details[I]}"
+  echo -en "Help file:      "; [[ -n ${this_details[H]} ]] && echo "${this_details[H]}.help" || echo ""
+  echo -e "\nPublic methods:"; for i in "${!this_details[@]}"; do [[ $i == P* ]] && echo " ${i:1} (objR${this_details[$i]})"; done
+  echo -e "\nPrivate methods:"; for i in "${!this_details[@]}"; do [[ $i == M* && $i != P* ]] && echo " ${i:1} (objR${this_details[$i]})"; done
+  echo -e "\nVariables:"; for i in "${!this_data[@]}"; do echo " ${i:1} (objV_${this_data[$i]})"; done
+ }' objC_Default obj-info
+
+# C) @obj@dictionary and obj-error-messages
+((${objects["ID@obj@dictionary"]:-0} == 0)) && obj @obj obj-create @dictionary \
  objC_Variable -g obj_folder="" \
  objC_Variable -g obj_source_file="" \
  objC_Variable -gA 'obj_dictionary=()' \
@@ -50,18 +54,14 @@
   } 
  }' \
  objC_Init obj-add-local-dictionary
-((${objects["IDobj-error-messages"]:-0} == 0)) && obj @obj-dictionary obj-create obj-error-messages \
+((${objects["IDobj-error-messages"]:-0} == 0)) && obj @obj@dictionary obj-create obj-error-messages \
  obj_folder="${obj_HOME}" obj_source_file=obj-error
  
-# E) Change error helper
+# D) Change error helper
 objError() { local i c=0 et="$(obj obj-error-messages translate "$1")"; shift; for i in "$@"; do ((c++)); et="${et//%A${c}%/$i}"; done; echo "$et"; }
 
-# F) @obj and --help
-((${objects["ID@obj"]:-0} == 0)) && obj @ obj-create @obj objC_Default "--help"
-((${objects["ID--help"]:-0} == 0)) && obj @obj obj-create --help
-
-# G) @obj-backup-variables
-((${objects["ID@obj-backup-variables"]:-0} == 0)) && obj @ obj-create @obj-backup-variables \
+# E) @obj@backup-variables
+((${objects["ID@obj@backup-variables"]:-0} == 0)) && obj @obj obj-create @backup-variables \
  objC_Variable -g obj_backupfile="" \
  objC_Public obj-restore '{ local i; : ${obj_backupfile:="${PWD}/${this[1]}.bak"}
   [[ -e ${obj_backupfile} ]] && while IFS= read -r; do
@@ -72,4 +72,6 @@ objError() { local i c=0 et="$(obj obj-error-messages translate "$1")"; shift; f
   echo -n "" > "${obj_backupfile}"
   for i in "${!this_data[@]}"; do w="$(declare -p objV_${this_data[$i]})"; echo "${i:1}=${w#*=}" >> "${obj_backupfile}"; done  
  }' \
- objC_Default obj-restore
+ objC_Public i @obj@info obj-info \
+ objC_Default obj-restore \
+ objC_Init obj-restore
